### ISSUE TITLE
GUI

### ISSUE THREAD

**Issue by Thomananas** [guysoft/RealtimePi#10]
Hello guysoft,

I really like your RealtimePi. Is it possible to set up a GUI without a new build ? 

Best Regards

**Comment by guysoft** [comment]
Hey,
Yes it is.
In OctoPi we have a script, which I think of shipping with RealtimePi too, it installs a gui for you.
You can download it and run it from:
https://github.com/guysoft/OctoPi/blob/devel/src/modules/octopi/filesystem/home/pi/scripts/install-desktop

**Comment by guysoft** [comment]
Another way around this is that you can now download the export tar.gz and extract it over an existing Rasbian image, see: https://github.com/guysoft/RealtimePi/releases/tag/0.3.0

Closing if no reply
