### ISSUE TITLE
all buster builds (nightly) broken - usb and networking dont work

### ISSUE THREAD

**Issue by sebastiannielsen** [guysoft/RealtimePi#19]
Tried the buster builds, none of them work, usb and networking is broken. This on a rpi 2B. Guess its because it lacks bluetooth and wifi support and the build tried to activate that without support.

Since I can neither connect to ssh (due to broken networking) or connect a keyboard (due to broken usb) im unable to provide any form of logs or debugging info.

**Comment by guysoft** [comment]
Hey, 
1. please providfe the exact file name of the zip you are using. There is a recent build `` 2019-08-24_2019-07-10-realtimepi-buster-lite-0.4.0.zip`` that might solve your issue. Without you providing I have no idea what you are testing.
2. The ``cmdline.txt`` has been changed in the nightly, please see:
https://github.com/raspberrypi/linux/issues/2943#issuecomment-507039882
The Rpi2 should work if you just update the ``cmdline.txt`` to how it looks in stable builds.

**Comment by sebastiannielsen** [comment]
Following filenames were tested and did NOT work:

2019-06-29_2019-06-20-realtimepi-buster-lite-0.4.0.zip
2019-08-24_2019-07-10-realtimepi-buster-lite-0.4.0.zip

I checked and the cmdline is already changed per the linked comment in those builds.

**Comment by guysoft** [comment]
Ok - did you try changing the ``cmdline.txt`` as given in the example?

**Comment by sebastiannielsen** [comment]
as I said, cmdline was already as in the example. With the dwc_otg.lpm_enable=1

**Comment by sebastiannielsen** [comment]
Now I tried with dwc_otg.lpm_enable=0 but the problem is that the boot process then stalls at finding /boot, then it can't find root filesystem, and then it starts emegency shell, afterwards it tries to sync NTP time but it can't since neither network or USB is working.

dwc_otg.lpm_enable=1 works booting from, but then usb and network don't work.

**Comment by guysoft** [comment]
@sebastiannielsen 
Ok, this is a known bug, and you need to report it to: https://github.com/raspberrypi/linux/issues/2943#issuecomment-507039882

**Comment by sebastiannielsen** [comment]
Should I report it there when the latest official build (Raspbian Lite official 2019-07-10) does work flawlessly without any problems, and without any changes to cmdline?

Because the bug only comes when using your rt build.

**Comment by guysoft** [comment]
The thing is that the RT branch is in low priority and is maintained by @TiejunChina . The Rpi kernel developers are not really looking in to RT stuff. The  ``usb-dwc_otg-fix`` which is suppose to make the system work both with USB and RT was writen by [Oussama Ghorbel <ghorbel@gmail.com>](https://www.osadl.org/monitoring/patches/r7s3/usb-dwc_otg-fix-system-lockup-when-interrupts-are-threaded.patch.html) which handle @oghorbel does not seem to be active.
I am not sure who has the technical knowhow to fix this. We might need a kernel developer to step in and save the day.

**Comment by sebastiannielsen** [comment]
How comes it that networking becomes borked by this fix?
I could live without USB if we could just get the networking to be happy.

or is the network card basically a USB network card "hardwired"`?

**Comment by guysoft** [comment]
The usb and ethernet share the same controller.

**Comment by sebastiannielsen** [comment]
@TiejunChina since the base repo (official raspberry repo) does not have any prebuilt RT binaries what I can see, I of course reported it here where the binaries where built.
The reason I want RT is that I intend running a NTP server and want as high accuracy as possible.

**Comment by guysoft** [comment]
@sebastiannielsen A realtime kernel is not relevant for an NTP server. You need a hardware element for a realtime clock. So as much as I value your debuging help, know its the wrong technology for your project.

**Comment by sebastiannielsen** [comment]
@guysoft and thats what I have, I have a GPS board with PPS output, and I also use the PPS kernel discipline. To improve the accuracy of this input processing of the PPS signal, I would want to use a RT kernel.

**Comment by guysoft** [comment]
Ah, my bad then. Didn't you are going all the way down to the signal processing of the PPS signal. There is code that does this freely available?

**Comment by sebastiannielsen** [comment]
yes, there is a kernel module that is shipped with the rpi image, that does all this signal processing and then exposes this as a /dev/pps0 device.

**Comment by guysoft** [comment]
Can't find where that kernel module needs a realtime kernel though:
https://www.worldtimesolutions.com/support/ntp/Debian_Lenny_Linux_PPS_support_for_ntpd.html

Will not this isn't related to the issue, just my general curiosity

**Comment by sebastiannielsen** [comment]
It doesnt NEED a realtime kernel, but it will of course perform better (ergo higher accuracy) by using a realtime kernel.

**Comment by guysoft** [comment]
I am not sure if it needs to specifically ask for non-preemptive scheduling inside the module. Unsure about that.

**Comment by guysoft** [comment]
Hey, this is news about this.
The is a new fork that solves the USB FIQ issues https://github.com/raspberrypi/linux/pull/3336
I have built a nightly based on it and would appreciate people testing:
http://unofficialpi.org/Distros/RealtimePi/nightly/2019-12-11_2019-09-26-realtimepi-buster-lite-0.4.0.zip

Might still not work in Pi4, but if it works on older versions it should not be an issue to add that.

**Comment by guysoft** [comment]
Has been solved in RC2 #20  thanks to https://github.com/raspberrypi/linux/pull/3336
