### ISSUE TITLE
Can't boot Pi 1B+ on recent images

### ISSUE THREAD

**Issue by korakios** [guysoft/RealtimePi#23]
Hi ,
I tried booting my Pi without plugging everything ,only the ethernet cable for ssh, but it freezes.
Only working image was 0.1 and 0.2 with 4.9.68-rt60 kernel

Edit: Should check #13 first, will post back

**Comment by korakios** [comment]
Booting with dwc_otg.lpm_enable=1 does boot v0.3 v0.4 ,but unfortunately without working usb ethernet

**Comment by guysoft** [comment]
1. What version of Raspberrypi?
2. Are you using v0.4 latest stable?
There was an issue here that was resolved on the latest stable release: https://github.com/raspberrypi/linux/pull/3336

You might want to report this here too: https://github.com/raspberrypi/linux/issues/2943

**Comment by korakios** [comment]
I tried the 0.4 from 
http://unofficialpi.org/Distros/RealtimePi/
_2019-12-17_2019-09-26-realtimepi-buster-lite-0.4.0.zip_
Haven't tried the nightly 0.5 yet.

**Comment by korakios** [comment]
Well , the 0.5 doesn't work either.
Tried the official Raspberry Pi OS (32-bit) Lite image ,it boots fine. 
I don't know if it helps, booting with _threadirqs_ option ,it also hangs . Maybe because the stock kernel doesn't support irq threading at all.

**Comment by guysoft** [comment]
Not really sure how to progress here, does it work on other devices for you?
Its a kernel issue which should be reported to the kernel, did you report it there in the end?

**Comment by korakios** [comment]
You mean about the threadirqs option on the stock kernel? Where should I report it (link)?

**Comment by guysoft** [comment]
Wrote it here in the thread:
https://github.com/guysoft/RealtimePi/issues/23#issuecomment-643748728
I linked two relevant issues.
This is the main page of the tracker, just in-case you didn't follow that:
https://github.com/raspberrypi/linux/issues

**Comment by guysoft** [comment]
Not maintaining 1B at the moment, it might work, in 0.5.0, but no one has reported that they tested it.
