### ISSUE TITLE
How would one get the `perf` tool included in the build

### ISSUE THREAD

**Issue by jpieper** [guysoft/RealtimePi#24]
Do you have any hints as to what would need to be modified to get `perf` into the image associated with the realtime kernel?

**Comment by guysoft** [comment]
The kernel is managed by a group of people on the RaspberryPi kenel fork, they have their own issue tracker, and you can ask there.
If perf is needed in the RT branch specifically then ask in one of the related issues there. This is the upcoming branch: https://github.com/raspberrypi/linux/issues/3625

**Comment by jpieper** [comment]
Thanks!
