### ISSUE TITLE
how to get the correct linux-headers?

### ISSUE THREAD

**Issue by NickNgHK** [guysoft/RealtimePi#25]
Hi @guysoft 
Thanks for the great work to make realtime Pi work.
May I know the right way to get the linux-headers in order to compile some application on the Pi?
If I use apt-get install linux-headers , I can't get the correct header...

Thanks a lot!

**Comment by guysoft** [comment]
Yes, at the moment its a little tricky.
If you know what version you are using you can see what ``KERNEL_COMMIT`` was used.
For example for ``0.4.0`` its:
https://github.com/guysoft/RealtimePi/blob/43fc2f52048c661d4938e54e9f16e88dcda5d1c2/src/modules/realtimepi/config#L6

Then you can take the sha1 there and just pull it from raspeberrypi source tree:
https://github.com/raspberrypi/linux/tree/e2e9cec6fb061ba58304fd391ef76747f2963557

**Comment by NickNgHK** [comment]
Hi @guysoft :
Thanks for the reply!
I googled the way to generate linux-headers

I got the following way:
====================
cd /usr/src
git clone --depth 1 https://github.com/raspberrypi/linux.git
ln -s linux linux-4.1.18-v7+
ln -s /usr/src/linux /lib/modules/4.1.18-v7+/build
cd linux
wget https://raw.githubusercontent.com/raspberrypi/firmware/master/extra/Module.symvers
make menuconfig
make prepare
make modules_prepare

=======================

I got couple of pain points ...
1. I am using your build environment , how can I find out the cross compile tool chains?
2. do it really necessary to download that unknown Module.symvers?
3. I tried to git clone the Linux source to my Pi Zero.. but I always failed to clone it completely , is that possible build the linux-headers directly at the host PC? 

With best regards,
Nick

**Comment by guysoft** [comment]
Closing as solved

**Comment by guysoft** [comment]
1. CustomPiOS emulates the device as and compiles, not a cross-compile.
2. I don't know what that is, I don't think so, it says in the url its a firmware.
3. "failed" is too board, what error are you getting? What happens after that?
