### ISSUE TITLE
Unable to boot RealtimePi OS with Raspberry Pi 4b

### ISSUE THREAD

**Issue by Chase1325** [guysoft/RealtimePi#26]
I am getting error messages such as 
'recover4.elf not found(6)'
'recovery.elf not found(6)'
This board requires newer software
Error: 00000044
Insert SD-CARD

**Comment by guysoft** [comment]
Its saying in its cryptic way that there is a hardware issue, either the card or power supply:
https://github.com/raspberrypi/firmware/issues/1468

> The significant error is the XHCI cmd error which might indicate a power issue e.g. try connecting to the SSD via a powered hub.

**Comment by guysoft** [comment]
Update, it seems like there was a commit that might address the issue, it will go the the nightly:
https://github.com/raspberrypi/linux/commit/1c082fa78a09436ff22f30bfc82b9b7a127686d5

**Comment by guysoft** [comment]
This might also be relevant:
https://github.com/raspberrypi/linux/issues/3625#issuecomment-747287384

Someone built it, but it seems the RT Rpi kernel maitnance keeps moving hands and I am not sure how to keep it steady.
Its like someone gets it from time to time to work and they they push it somewhere.

**Comment by Chase1325** [comment]
If I were to follow the instructions to do a 6 hr build myself (below commands in Ubuntu) would you expect it to make a working version? Or did you mean before that you were planning to upload a stable version to 'nightly'?

**sudo apt-get install realpath p7zip-full qemu-user-static

git clone https://github.com/guysoft/CustomPiOS.git
git clone https://github.com/guysoft/RealtimePi.git
cd RealtimePi/src/image
wget -c --trust-server-names 'https://downloads.raspberrypi.org/raspbian_lite_latest'
cd ..
../../CustomPiOS/src/update-custompios-paths
sudo modprobe loop
sudo bash -x ./build_dist**

**Comment by guysoft** [comment]
I am running it on my build system. The one on the main readme page. 
You are welcome to build it, but you don't have to.

**Comment by guysoft** [comment]
Build is ready, you can test it:
http://unofficialpi.org/Distros/RealtimePi/nightly/2021-03-16_2021-01-11-realtimepi-buster-armhf-lite-0.5.0.zip

Md5:
http://unofficialpi.org/Distros/RealtimePi/nightly/2021-03-16_2021-01-11-realtimepi-buster-armhf-lite-0.5.0.zip.md5

**Comment by Chase1325** [comment]
Thanks for being so quick to do a new update! It seemed to fix some of the issues, but some are still present. It looks like its a clock issue and gpio:

bcm2835-cpufreq:bcm2835_get_clock:93: Failed to get clock (-12)
cpufreq: cpufreq_online: ->get() failed

^That repeats 4 times. Then I get:
raspberrypi-exp-gpio soc:firmware:gpio: Failed to get GPIO 4 config (-12 84)
gpio-regulator sd_io_1v8_reg: Could not obtain regulator setting GPIOs: -12

**Comment by guysoft** [comment]
Does it boot?

**Comment by Chase1325** [comment]
No those are messages that come across in the boot sequence

**Comment by Chase1325** [comment]
Also, I used the same microSD image on my 3B and it worked just fine and booted up... something specific to the 4b

**Comment by wschilling** [comment]
I am seeing a similar problem with my P 4B.  Here is a screen shot of the boot messages I see: 
![WIN_20210605_17_05_56_Pro](https://user-images.githubusercontent.com/28993106/120906622-9bcba600-c620-11eb-8906-e85c299f351e.jpg)

**Comment by guysoft** [comment]
I'd imagine its a new hardware configuration, the image needs to be updated to a newer kernel and firmware, and I didn't get any time to do that.

**Comment by guysoft** [comment]
Closing, use 0.5.0
