### ISSUE TITLE
Updated PREEMPT_RT kernel 5.10.52-rt47

### ISSUE THREAD

**Issue by kdoren** [guysoft/RealtimePi#30]
I posted a build of PREEMPT_RT kernel 5.10.52-rt47 here:  https://github.com/kdoren/linux/releases/tag/rpi_5.10.52-rt47
It's looking pretty solid - no thread lockups on multithreaded jamulus server.
Latency plots are here:  https://github.com/kdoren/linux/discussions/11

**Comment by guysoft** [comment]
Thanks, updated and now started a new build
