### ISSUE TITLE
Keyboard mapping

### ISSUE THREAD

**Issue by handsomir** [guysoft/RealtimePi#37]
Aloha Guy, 

Thank you for providing the compiled realtimepi kernel. I have been experimenting with it for a couple of days and I am writing to l;et you know about a peculiarity of the set up. I have noticed it in both 0.5.0 and 0.6.0 buster distros.

I believe that the default keyboard mapping is set to a locale other than US. I changed the default pi account password to one with a lot of special characters using a US keyboard directly connected to the Pi. A few minutes later I tried to ssh to the Pi from another machine with, yet another, US keyboard. To my surprise the password was rejected every time. It took me a few tries to figure out that the default locale might be GB and only because the British pound symbol showed up when I tried to type `#`.

I cleared the hurdle with 

`$ localectl set-keymap us`

and I've been happily performing `cyclictest`s ever since.

Since I haven't seen anything about keyboard mappings mentioned in the README I thought it might be worth bringing it up here. 

Cheers,
BUI

**Comment by guysoft** [comment]
Raspberry Pi OS default is keyboard is UK.
Its not part of RealtinePi. Its set in the official rou repo. See https://github.com/RPi-Distro/pi-gen/blob/5d044ba71b7eba33860fdbf222a9a29ae42691e9/README.md#config
KEYBOARD_LAYOUT section

**Comment by handsomir** [comment]
Thank you! It makes perfect sense now.
