### ISSUE TITLE
Add possibility to apply custom patches

### ISSUE THREAD

**Issue by robiwano** [guysoft/RealtimePi#5]
I'd like to build the RealtimePi image, but in addition to the RT patches, I'd like to add my own patches.

**Comment by guysoft** [comment]
If you want to try it quick and dirty I'd suggest editing https://github.com/guysoft/RealtimePi/blob/devel/src/modules/realtimepi/start_chroot_script direcly, you can also add files to https://github.com/guysoft/RealtimePi/blob/devel/src/modules/realtimepi/start_chroot_script .

If you want it slow and tidy I'd suggest you create a module that goes in config so you could change:
```
export MODULES="base(network,kernel(realtimepi))
```
to
```
export MODULES="base(network,kernel(realtimepi, my-kernel-patches))"
```
And keep it separate from realtimepi and maintain it.
[You can read more about modules here](https://github.com/guysoft/CustomPiOS/wiki/Modules).

**Comment by guysoft** [comment]
@robiwano see you are advancing, should I close this?

**Comment by robiwano** [comment]
Yup, do so.
