### ISSUE TITLE
How to build only the v6 flavored image

### ISSUE THREAD

**Issue by robiwano** [guysoft/RealtimePi#6]
The doc says it take ~12hours to build both kernels, but I need only the v6. I probably missed the docs on how to instruct build to build only for v6 ?

**Comment by guysoft** [comment]
In the config file. Or create your config.local file set

```
KERNEL_TYPE=v6
```

The default setting is in: https://github.com/guysoft/CustomPiOS/blob/CustomPiOS/src/modules/kernel/config

Its not well documented, i admit. 

We could add it to the README.

**Comment by robiwano** [comment]
Thank you, great!!

**Comment by guysoft** [comment]
I can fix it, but FYI pull requests are welcome.

**Comment by guysoft** [comment]
No, edit it in the config file like I wrote above. Your environment may change when using vagrant and such.

**Comment by guysoft** [comment]
Ok, closing, also fixed the bug reported: https://github.com/guysoft/CustomPiOS/issues/17
