### ISSUE TITLE
wifi configuration difficulty

### ISSUE THREAD

**Issue by gef01** [guysoft/RealtimePi#7]
I am having trouble setting up wifi and having it automatically come up on boot.

I have separately tried editing realtimepi-wpa-supplicant.txt and realtimepi-network.txt to have my wifi ssid and key. I have also changed both. From reading the comments in realtimepi-network.txt it seems that only thins file needs to be edited for a single ssid setup.

I cannot however get the wlan going – neither automaticall at boot or manually via iwconfig or ifconfig or iw

What i have for the realtimepi-wpa-supplicant.txt, I put identical info to what I used with a standard raspbian install:

code:
```
country=US
ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev
update_config=1

network={                                        #edited: typo in original post. was Network={
    ssid="myssid"
    psk="mypassword"
    key_mgmt=WPA-PSK
}
```

for realtimepi-network.txt I used:
code:
```
auto wlan0
iface wlan0 inet dhcp
    wpa-ssid "myssid"
    wpa-psk "mypassword"
```

Some help would be greatly appreciated.

Thank you

G

**Comment by guysoft** [comment]
What Raspberrypi are you using? Is this built in wifi or a dongle?
Are you using at least a 2A power supply and a GOOD usb cable (that tends to be the most common problem).
Have you tried, just for a test, to use an ethernet cable?

**Comment by gef01** [comment]
This has been tried several combinations of the files on both a pi 3 and a pi zero W. Both with built in wifi.
I have successfully used the same hardware with a standard raspbian image on both the 3 and the  zero W. I have also had success with two different power supplies. I am confident that I have good power and a good cable.
I have tried an ethernet cable on the pi 3. It works just fine wired, but I am unable to get the wireless to start up, even from the command line.

Is there something wrong with the configurations that I put in the original post? What should they be?

Do I need both files or just one? If one, which one? and if one, should I delete the other?

I am trying to have the pi bring up the wifi at startup using dhcp to get the ip address. I plan to use this in an embedded setting where cables are not practical.

Thank you once again.

G

**Comment by guysoft** [comment]
Yes, I spotted something, network should be in small letters:
```
network={
  ssid="Your Wifi SSID"
  psk="supersecretwifipassword"
}
```
Please use the provided example and that comes with RealtimePi.
Also, revert all changes in ``realtimepi-network.txt``, Its going to be dropped next release.

**Comment by gef01** [comment]
I believe that was a typo in the issue submission, but I'll check it when I get home. I actually copied that information from a working wpa_supplicant.conf for raspbian into realtimepi-wpa-supplicant.txt.

Thank you, I'll reply after I get to check the actual file.

G

**Comment by gef01** [comment]
My actual file is as it should be ( i obscured the ssid and psk:

```
pi@realtimepi:/boot $ more realtimepi-wpa-supplicant.txt
country=US
ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev
update_config=1
network={
       ssid="xxxxxxxxxx"
       psk="yyyyyyyyyy"
       key_mgmt=WPA-PSK
    }
```

**Comment by gef01** [comment]
I now have the original realtimepi-network.txt and the above realtimepi-wpa-supplicant.txt. 

This is what I get on startup:

```
pi@realtimepi:~ $ iwconfig
lo        no wireless extensions.

eth0      no wireless extensions.

wlan0     IEEE 802.11  ESSID:off/any
          Mode:Managed  Access Point: Not-Associated   Tx-Power=31 dBm
          Retry short limit:7   RTS thr:off   Fragment thr:off
          Power Management:on

pi@realtimepi:~ $ more /etc/wpa_supplicant/wpa_supplicant.conf
country=US
ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev
update_config=1
network={
       ssid="xxxxxxxxxx"
       psk="yyyyyyyyyy"
       key_mgmt=WPA-PSK
    }
```

It appears that thereis no hardware issue. iwlist scan finds my ssid and all of the others in the area:

```
sudo iwlist scan
lo        Interface doesn't support scanning.

eth0      Interface doesn't support scanning.

wlan0     Scan completed :
          Cell 01 - Address: 18:B8:0F:B5:35:AF
                    Channel:3
                    Frequency:2.422 GHz (Channel 3)
                    Quality=70/70  Signal level=-16 dBm
                    Encryption key:on
                    ESSID:"xxxxxxxxxx"
...
          Cell 02 - Address: 80:30:DC:4F:3E:BD
                    Channel:1
                    Frequency:2.412 GHz (Channel 1)
                    Quality=48/70  Signal level=-62 dBm
                    Encryption key:on
                    ESSID:""
...
```

**Comment by guysoft** [comment]
Strange, I can build another nightly if that helps, we tweaked a bit some of the network settings, but nothing that should effect this. Not sure what to do beyond that, you can try configuring it like you would configure raspbian-lite images. Its actually what this is:
https://thepihut.com/blogs/raspberry-pi-tutorials/83502916-how-to-setup-wifi-on-raspbian-jessie-lite

**Comment by gef01** [comment]
I am using the stretch-lite version: 
2017-12-20_2017-11-29-realtimepi-stretch-lite-0.2.zip

I have tried setting it up like a standard raspbian stretch lite. No difference.

This is from /var/log/syslog:

```
var/log/syslog:Mar  9 14:50:31 realtimepi kernel: [   12.620470] IPv6: ADDRCONF(NETDEV_UP): wlan0: link is not ready
var/log/syslog:Mar  9 14:50:31 realtimepi dhcpcd[393]: wlan0: waiting for carrier
var/log/syslog:Mar  9 14:50:31 realtimepi dhcpcd[393]: wlan0: carrier acquired   <--------
var/log/syslog:Mar  9 14:50:31 realtimepi dhcpcd[393]: wlan0: IAID eb:c6:88:d5
var/log/syslog:Mar  9 14:50:32 realtimepi dhcpcd[393]: wlan0: adding address fe80::99c9:df0a:f2c4:4327
var/log/syslog:Mar  9 14:50:32 realtimepi dhcpcd[393]: wlan0: carrier lost   <--------
var/log/syslog:Mar  9 14:50:32 realtimepi dhcpcd[393]: wlan0: deleting address fe80::99c9:df0a:f2c4:4327
```
Note the 2 specified lines. I am not sure what to make of this.

Any ideas?

**Comment by guysoft** [comment]
If you tried with standard raspbian lite then its not a RealtimePi issue, its a raspbian issue. RealtimePi just takes the kernel of rasbian lite and compiles it with a realtime patch. You can ask for support at raspbian.

**Comment by gef01** [comment]
I was not very clear. I tried setting up realtimepi like a standard raspbian stretch lite. That did not make any difference. The wifi did not work. I have no trouble and everything works with raspbian stretch lite.

**Comment by guysoft** [comment]
Has this been resolved? Can I close this? Closing if no reply.

**Comment by gef01** [comment]
I still cannot get the Network to work even with the newest version that you released after the introduction of the pi 3B+. 

----- Original Message -----

**Comment by guysoft** [comment]
I just noticed you said in the last message that raspbian didn't work neither. This means this not anan issue with RealtimePi and is with rasbian or your hardware.  So you should get support in Raspberrypi support channels. I have exhausted what I can do.

**Comment by gef01** [comment]
Raspbian worked just fine. I never had an issue with Raspbian.

This is what I said:

> I was not very clear. I tried setting up realtimepi like a standard raspbian stretch lite. That did not make any difference. The wifi did not work. **_I have no trouble and everything works with raspbian stretch lite_.**

I have tried setting it up for a Pi 0W and a Pi 3B. I have set it up according to the example given and separately similar to a standard stretch lite install. Nothing has worked to get RealtimePi to connect to a wireless network.

**Comment by guysoft** [comment]
Looks like origial poster solved the issue, with no explanation why, so closing if no reply

**Comment by Patrickyp** [comment]
I also have a question.  So is the file that I need to edit in /rootfs/var/run/wpa_supplicant ?  I cannot access that folder says "You do not have permission necessary to view the contents of.." when I am using the sd card as a flash drive.

**Comment by guysoft** [comment]
@Patrickyp No, [please read the reademe file](https://github.com/guysoft/RealtimePi#how-to-use-it). Closing.
